export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';

export const NOTIFICATION = 'NOTIFICATION';
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION';

export const STATUS_PENDING = 'STATUS_PENDING';
export const STATUS_COMPLETE = 'STATUS_COMPLETE';

export const BUSINESS_LIST_RECEIVED = 'BUSINESS_LIST_RECEIVED';
export const ROUTE_LIST_RECEIVED = 'ROUTE_LIST_RECEIVED';
export const REMOVE_BUSINESS_SUCCESS = 'REMOVE_BUSINESS_SUCCESS';
export const REMOVE_BUSINESS_FAILURE = 'REMOVE_BUSINESS_FAILURE';

export const GET_USER_LIST = 'GET_USER_LIST';

export const GET_ITEM_MASTER = 'GET_ITEM_MASTER';

export const CHECKINS_RECEIVED = 'CHECKINS_RECEIVED';